In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
%load_ext kedro.ipython

The kedro.ipython extension is already loaded. To reload it, use:
  %reload_ext kedro.ipython

In [4]:
df = catalog.load("raw_train_dev")
df.head()

[03/27/25 21:54:09] INFO     Loading data from raw_train_dev (ParquetDataset)...                ]8;id=317254;file:///home/leo/.pyenv/versions/3.12.9/envs/kobe/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=732544;file:///home/leo/.pyenv/versions/3.12.9/envs/kobe/lib/python3.12/site-packages/kedro/io/data_catalog.py#401\401]8;;\

,action_type,combined_shot_type,game_event_id,game_id,lat,loc_x,loc_y,lon,minutes_remaining,period,...,shot_type,shot_zone_area,shot_zone_basic,shot_zone_range,team_id,team_name,game_date,matchup,opponent,shot_id
0,Jump Shot,Jump Shot,10,20000012,33.9723,167,72,-118.1028,10,1,...,2PT Field Goal,Right Side(R),Mid-Range,16-24 ft.,1610612747,Los Angeles Lakers,2000-10-31,LAL @ POR,POR,1
1,Jump Shot,Jump Shot,12,20000012,34.0443,-157,0,-118.4268,10,1,...,2PT Field Goal,Left Side(L),Mid-Range,8-16 ft.,1610612747,Los Angeles Lakers,2000-10-31,LAL @ POR,POR,2
2,Jump Shot,Jump Shot,35,20000012,33.9093,-101,135,-118.3708,7,1,...,2PT Field Goal,Left Side Center(LC),Mid-Range,16-24 ft.,1610612747,Los Angeles Lakers,2000-10-31,LAL @ POR,POR,3
3,Jump Shot,Jump Shot,43,20000012,33.8693,138,175,-118.1318,6,1,...,2PT Field Goal,Right Side Center(RC),Mid-Range,16-24 ft.,1610612747,Los Angeles Lakers,2000-10-31,LAL @ POR,POR,4
4,Driving Dunk Shot,Dunk,155,20000012,34.0443,0,0,-118.2698,6,2,...,2PT Field Goal,Center(C),Restricted Area,Less Than 8 ft.,1610612747,Los Angeles Lakers,2000-10-31,LAL @ POR,POR,5

In [9]:
df.describe()

,game_event_id,game_id,lat,loc_x,loc_y,lon,minutes_remaining,period,playoffs,seconds_remaining,shot_distance,shot_made_flag,team_id,shot_id
count,20285.000000,2.028500e+04,20285.000000,20285.000000,20285.000000,20285.000000,20285.000000,20285.000000,20285.000000,20285.000000,20285.000000,20285.000000,2.028500e+04,20285.000000
mean,240.655016,2.480663e+07,33.980645,7.489721,63.654967,-118.262310,5.100173,2.471974,0.148731,28.736357,10.216317,0.477348,1.610613e+09,15128.758738
std,148.298291,7.795114e+06,0.065895,93.401493,65.894551,0.093401,3.423866,1.148192,0.355831,17.429026,7.559547,0.499499,0.000000e+00,9008.851004
min,2.000000,2.000001e+07,33.543300,-218.000000,-44.000000,-118.487800,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.610613e+09,2.000000
25%,103.000000,2.040092e+07,33.926300,-43.000000,0.000000,-118.312800,2.000000,1.000000,0.000000,14.000000,1.000000,0.000000,1.610613e+09,7157.000000
50%,245.000000,2.090013e+07,33.999300,0.000000,45.000000,-118.269800,5.000000,3.000000,0.000000,29.000000,12.000000,0.000000,1.610613e+09,15064.000000
75%,354.000000,2.960098e+07,34.044300,75.000000,118.000000,-118.194800,8.000000,3.000000,0.000000,44.000000,17.000000,1.000000,1.610613e+09,23224.000000
max,653.000000,4.990009e+07,34.088300,220.000000,501.000000,-118.049800,11.000000,7.000000,1.000000,59.000000,50.000000,1.000000,1.610613e+09,30697.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24271 entries, 0 to 30696
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   action_type         24271 non-null  object
 1   combined_shot_type  24271 non-null  object
 2   game_event_id       24271 non-null  int64
 3   game_id             24271 non-null  int64
 4   lat                 24271 non-null  float64
 5   loc_x               24271 non-null  int64
 6   loc_y               24271 non-null  int64
 7   lon                 24271 non-null  float64
 8   minutes_remaining   24271 non-null  int64
 9   period              24271 non-null  int64
 10  playoffs            24271 non-null  int64
 11  season              24271 non-null  object
 12  seconds_remaining   24271 non-null  int64
 13  shot_distance       24271 non-null  int64
 14  shot_made_flag      20285 non-null  float64
 15  shot_type           24271 non-null  object
 16  shot_zone_area      24271 non-null  object
 17  shot_zone_basic     24271 non-null  object
 18  shot_zone_range     24271 non-null  object
 19  team_id             24271 non-null  int64
 20  team_name           24271 non-null  object
 21  game_date           24271 non-null  object
 22  matchup             24271 non-null  object
 23  opponent            24271 non-null  object
 24  shot_id             24271 non-null  int64
dtypes: float64(3), int64(11), object(11)
memory usage: 4.8+ MB

In [6]:
df.dropna(inplace=True)

In [7]:
#plot the loc x and loc y color based on shot_made_flag
# plt.figure(figsize=(10,10))
# plt.scatter(df.lon, df.lat, c=df.shot_made_flag, cmap='RdYlGn', s=20, alpha=0.6, edgecolors='black')
# plt.show()

In [11]:
df = df[['lat', 'lon', 'minutes_remaining', 'period', 'playoffs', 'shot_distance', 'shot_made_flag']]
df

,lat,lon,minutes_remaining,period,playoffs,shot_distance,shot_made_flag
1,34.0443,-118.4268,10,1,0,15,0.0
2,33.9093,-118.3708,7,1,0,16,1.0
3,33.8693,-118.1318,6,1,0,22,0.0
4,34.0443,-118.2698,6,2,0,0,1.0
5,34.0553,-118.4148,9,3,0,14,0.0
...,...,...,...,...,...,...,...
30690,33.9443,-118.3828,11,4,1,15,0.0
30691,34.0443,-118.2698,7,4,1,0,0.0
30692,33.9963,-118.2688,6,4,1,4,0.0
30694,33.8783,-118.4038,3,4,1,21,1.0
30696,33.9723,-118.2688,0,4,1,7,0.0